### ISSUE TITLE
Suggestion to make the highlight adaptive to ColorScheme event.

### ISSUE THREAD

**Issue by bassamsdata** [mcauley-penney/visual-whitespace.nvim#28]
Thank you for this plugin.

As the title suggests, when changing the colorscheme using the `:colorscheme` command, the plugin causes the selection to appear off because the new colorscheme clears the highlights. This behavior is shown below. 

![Screen Recording 2024-12-01 at 11 29 05 PM](https://github.com/user-attachments/assets/3fdee3cf-0938-4bb3-aad1-187790c66c13)

It would be great to add an autocommand for the `ColorScheme` event to reapply the highlights.

Thank you!

**Comment by mcauley-penney** [comment]
Good spot, that's an oversight on my part. I rarely change color schemes, so I didn't even think of this. I will take care of this during my day tomorrow

**Comment by johnpgr** [comment]
And this would fix a issue that happens if you set your colorscheme after the plugin loads. Where the visual selection of the whitespace chars have the same background as the normal background like in the video demostrating this in this issue.
![image](https://github.com/user-attachments/assets/ec5af657-c13a-4f22-9e7e-6e570e5a1fa9)
This is how my `init.lua` is set. This makes this plugin always have wrong highlights.

**Comment by mcauley-penney** [comment]
I just pushed a commit to main that should fix this. Please test it out and let me know how it works!

**Comment by bassamsdata** [comment]
Thank you! Would you mind pushing it to the `incremental-hl` branch, please, as that's the branch I'm using.

**Comment by mcauley-penney** [comment]
I'd be happy to! I wanted to confirm it works on main first before proliferating it elsewhere. It's a fix that will go into every branch

**Comment by bassamsdata** [comment]
I just tried it, and it works perfectly when changing colorschemes during the session.

**Comment by mcauley-penney** [comment]
@bassamsdata Just merged this into `incremental-hl`

**Comment by bassamsdata** [comment]
Thank you, appreciated . it works with no issues.
